---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: loki-s3-credentials
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: loki-s3-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      type: Opaque
      data:
        LOKI_S3_ACCESS_KEY: "{{ .accessKey }}"
        LOKI_S3_SECRET_KEY: "{{ .secretKey }}"
  data:
    - secretKey: accessKey
      remoteRef:
        key: secret/minio/loki-s3
        property: access_key
    - secretKey: secretKey
      remoteRef:
        key: secret/minio/loki-s3
        property: secret_key
