apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: monitoring
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`grafana.lan.e-dani.com`)
      middlewares:
        - name: authelia
          namespace: authelia
      services:
        - name: vm-grafana
          port: 80
  tls:
    secretName: wildcard-lan-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`alertmanager.lan.e-dani.com`)
      middlewares:
        - name: authelia
          namespace: authelia
      services:
        - name: vmalertmanager-vm-victoria-metrics-k8s-stack
          port: 9093
  tls:
    secretName: wildcard-lan-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vmsingle
  namespace: monitoring
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`vm.lan.e-dani.com`)
      middlewares:
        - name: authelia
          namespace: authelia
      services:
        - name: vmsingle-vm-victoria-metrics-k8s-stack
          port: 8428
  tls:
    secretName: wildcard-lan-tls
